### PR TITLE
add TypedDataConvert to message

### PR DESCRIPTION
**Pull request by marktohark**
## What was wrong?

I get sign json from blur.io
when sign json convert to py dict, I need to fix value type manually.

## How was it fixed?
Add a helper to message.py

```python
import json
from eth_account.messages import encode_structured_data, TypedDataConvert

s1 = '''{"type":"signTypedData_v4","data":{"domain":{"name":"Blur Exchange","version":"1.0","chainId":1,"verifyingContract":"0x000000000000ad05ccc4f10045630fb830b95127"},"types":{"Order":[{"name":"trader","type":"address"},{"name":"side","type":"uint8"},{"name":"matchingPolicy","type":"address"},{"name":"collection","type":"address"},{"name":"tokenId","type":"uint256"},{"name":"amount","type":"uint256"},{"name":"paymentToken","type":"address"},{"name":"price","type":"uint256"},{"name":"listingTime","type":"uint256"},{"name":"expirationTime","type":"uint256"},{"name":"fees","type":"Fee[]"},{"name":"salt","type":"uint256"},{"name":"extraParams","type":"bytes"},{"name":"nonce","type":"uint256"}],"Fee":[{"name":"rate","type":"uint16"},{"name":"recipient","type":"address"}]},"value":{"trader":"0xcb672216a6290ea85cdf75d3b8cbd18c99cac50e","side":0,"matchingPolicy":"0x0000000000b92d5d043faf7cecf7e2ee6aaed232","collection":"0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d","tokenId":"0","amount":"1","paymentToken":"0x0000000000a39bb272e79075ade125fd351887ac","price":"10000000000000000","listingTime":1678256751,"expirationTime":1709792748,"fees":[],"salt":"0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000d61099c9f51e5d0332a4a44cf2aa174b","extraParams":"0x01","nonce":"0"}}}'''

s1 = json.loads(s1)

signInfo = TypedDataConvert(s1['data']['domain'], s1['data']['types'], s1['data']['value'])
encodeData = encode_structured_data(signInfo)
res = web3.auto.w3.eth.account.sign_message(encodeData, private_key=pk)
print(res.signature.hex())
```

### CODE REVIEW

**Comment by snarflakes** [comment]
this is exactly what I'm looking for.  It is difficult to understand what parts of the eth_signedTypeData request are needed to properly complete the signature using encode_structured_data. Can't wait for this to merge and read up on the documentation.

**Comment by marktohark** [comment]
> gnosis safe signtypeddata

would you give me "gnosis safe" website!?
I can try and debug.
I only try on blur.io, so i thought that it is generic code.

**Comment by snarflakes** [comment]
Of course!

[](https://app.safe.global/welcome)

The lead multi-sig contract wallet out there. So pretty significant player. Let me know if i can help.

**Comment by snarflakes** [comment]
> > gnosis safe signtypeddata
> 
> 
> 
> would you give me "gnosis safe" website!?
> 
> I can try and debug.
> 
> I only try on blur.io, so i thought that it is generic code.
> 
> 
> 
> Or you can post a sign info json here.
> 
> P.S. if you can provide after sign result for compare

This whole data converting system must be considerably complicated for metamask to have a whole repo to detailing with this.

[](https://docs.metamask.io/guide/signing-data.html#signtypeddata-v4)

The eth-sig-util repo [](https://github.com/MetaMask/eth-sig-util) looks to contain all the signature structuring code in javascript only 🙄.

**Comment by pacrob** [comment]
Thanks for the PR! I'll be looking at this this week. It would certainly be useful to be able to convert from/to others' EIP712 implementations.

**Comment by marktohark** [comment]
i cannot get signInfo from safe.global.
i use example from your issue↓ #220  
image

```python
import json
from eth_account.messages import encode_structured_data
from eth_account import Account

def _fixInt(v):
    if type(v) == str:
        base = 16 if '0x' in v else 10
        return int(v, base)
    elif type(v) == int:
        return v
    return None


def _fixByte(v):
    if type(v) == str and len(v) % 2 == 0:
        newValue = v
        if '0x' in v:
            newValue = newValue.replace('0x', '')
        return bytes.fromhex(newValue)
    elif type(v) == list:
        testList = [0 <= _v <= 255 for _v in v]
        if all(testList):
            return bytes(v)
    return None


def _fix(v, tp, types):
    isArray = '[' in tp and ']' in tp
    if isArray:
        tp = tp[:tp.index('[')]
    if tp in ['uint8', 'uint16', 'uint32', 'uint64', 'uint128', 'uint256', 'uint512', 'int8', 'int16', 'int32', 'int64',
              'int128', 'int256', 'int512']:
        if isArray:
            r = []
            for i, _ in enumerate(v):
                newV = _fixInt(v[i])
                if newV is not None:
                    r.append(newV)
                else:
                    return None
            return r
        else:
            return _fixInt(v)

    elif tp in ['bytes1', 'bytes32', 'bytes']:
        if isArray:
            r = []
            for i, _ in enumerate(v):
                newV = _fixByte(v[i])
                if newV is not None:
                    r.append(newV)
                else:
                    return None
            return r
        else:
            return _fixByte(v)
    elif tp == 'address':
        return v
    elif tp == 'string':
        return v
    else:  # custom type
        if not (tp in types):
            return None
        newTypes = types[tp]
        if isArray:
            r = []
            for i, _ in enumerate(v):
                newV = {}
                for tInfo in newTypes:
                    key = tInfo['name']
                    tp = tInfo['type']
                    newV[key] = _fix(v[i][key], tp, types)
                r.append(newV)
            return r
        else:
            newV = {}
            for tInfo in newTypes:
                key = tInfo['name']
                tp = tInfo['type']
                newV[key] = _fix(v[key], tp, types)
            return newV


def _getPrimaryType(types: dict, values: dict):
    primaryType = ''
    for typeKey in types:
        vTypes = types[typeKey]
        ok = True
        for vType in vTypes:
            if vType['name'] not in values:
                ok = False
                break
        if ok:
            primaryType = typeKey
            break
    if primaryType == '':
        return None
    return primaryType


def TypedDataConvert(domain: dict, types: dict, values: dict):
    EIP712DomainMap = {
        'name': {'name': 'name', 'type': 'string'},
        'version': {'name': 'version', 'type': 'string'},
        'chainId': {'name': 'chainId', 'type': 'uint256'},
        'verifyingContract': {'name': 'verifyingContract', 'type': 'address'},
        'salt': {'name': 'salt', 'type': 'bytes32'},
    }
    primaryType = _getPrimaryType(types, values)
    newValue = _fix(values.copy(), primaryType, types)
    EIP712Domain = []
    for domainKey in domain:
        EIP712Domain.append(EIP712DomainMap[domainKey])
    newTypes = types.copy()
    newTypes['EIP712Domain'] = EIP712Domain
    newDomain = _fix(domain, 'EIP712Domain', newTypes)
    completedStruct = {
        "types": newTypes,
        "domain": newDomain,
        "message": newValue,
        "primaryType": primaryType,
    }
    return completedStruct

s1 = '''{"types":{"SafeTx":[{"type":"address","name":"to"},{"type":"uint256","name":"value"},{"type":"bytes","name":"data"},{"type":"uint8","name":"operation"},{"type":"uint256","name":"safeTxGas"},{"type":"uint256","name":"baseGas"},{"type":"uint256","name":"gasPrice"},{"type":"address","name":"gasToken"},{"type":"address","name":"refundReceiver"},{"type":"uint256","name":"nonce"}],"EIP712Domain":[{"name":"chainId","type":"uint256"},{"name":"verifyingContract","type":"address"}]},"domain":{"chainId":"137","verifyingContract":"0x9135a7832db16190475f409b649771532bb6fa7f"},"primaryType":"SafeTx","message":{"to":"0x9135a7832db16190475f409b649771532bb6fa7f","value":"0","data":"0x694e80c30000000000000000000000000000000000000000000000000000000000000001","operation":"0","safeTxGas":"0","baseGas":"0","gasPrice":"0","gasToken":"0x0000000000000000000000000000000000000000","refundReceiver":"0x0000000000000000000000000000000000000000","nonce":"0"}}'''
s1 = json.loads(s1)

signInfo = TypedDataConvert(s1['domain'], s1['types'], s1['message'])
encodeData = encode_structured_data(signInfo)

res = Account.sign_message(encodeData, private_key='YOUR_PRIVATE_KEY')
print(res.signature.hex())
```
is it correct!?

**Comment by snarflakes** [comment]
> i cannot get signInfo from safe.global. i use example from your issue↓ #220 image
> 
> ```python
> import json
> from eth_account.messages import encode_structured_data
> from eth_account import Account
> 
> def _fixInt(v):
>     if type(v) == str:
>         base = 16 if '0x' in v else 10
>         return int(v, base)
>     elif type(v) == int:
>         return v
>     return None
> 
> 
> def _fixByte(v):
>     if type(v) == str and len(v) % 2 == 0:
>         newValue = v
>         if '0x' in v:
>             newValue = newValue.replace('0x', '')
>         return bytes.fromhex(newValue)
>     elif type(v) == list:
>         testList = [0 <= _v <= 255 for _v in v]
>         if all(testList):
>             return bytes(v)
>     return None
> 
> 
> def _fix(v, tp, types):
>     isArray = '[' in tp and ']' in tp
>     if isArray:
>         tp = tp[:tp.index('[')]
>     if tp in ['uint8', 'uint16', 'uint32', 'uint64', 'uint128', 'uint256', 'uint512', 'int8', 'int16', 'int32', 'int64',
>               'int128', 'int256', 'int512']:
>         if isArray:
>             r = []
>             for i, _ in enumerate(v):
>                 newV = _fixInt(v[i])
>                 if newV is not None:
>                     r.append(newV)
>                 else:
>                     return None
>             return r
>         else:
>             return _fixInt(v)
> 
>     elif tp in ['bytes1', 'bytes32', 'bytes']:
>         if isArray:
>             r = []
>             for i, _ in enumerate(v):
>                 newV = _fixByte(v[i])
>                 if newV is not None:
>                     r.append(newV)
>                 else:
>                     return None
>             return r
>         else:
>             return _fixByte(v)
>     elif tp == 'address':
>         return v
>     elif tp == 'string':
>         return v
>     else:  # custom type
>         if not (tp in types):
>             return None
>         newTypes = types[tp]
>         if isArray:
>             r = []
>             for i, _ in enumerate(v):
>                 newV = {}
>                 for tInfo in newTypes:
>                     key = tInfo['name']
>                     tp = tInfo['type']
>                     newV[key] = _fix(v[i][key], tp, types)
>                 r.append(newV)
>             return r
>         else:
>             newV = {}
>             for tInfo in newTypes:
>                 key = tInfo['name']
>                 tp = tInfo['type']
>                 newV[key] = _fix(v[key], tp, types)
>             return newV
> 
> 
> def _getPrimaryType(types: dict, values: dict):
>     primaryType = ''
>     for typeKey in types:
>         vTypes = types[typeKey]
>         ok = True
>         for vType in vTypes:
>             if vType['name'] not in values:
>                 ok = False
>                 break
>         if ok:
>             primaryType = typeKey
>             break
>     if primaryType == '':
>         return None
>     return primaryType
> 
> 
> def TypedDataConvert(domain: dict, types: dict, values: dict):
>     EIP712DomainMap = {
>         'name': {'name': 'name', 'type': 'string'},
>         'version': {'name': 'version', 'type': 'string'},
>         'chainId': {'name': 'chainId', 'type': 'uint256'},
>         'verifyingContract': {'name': 'verifyingContract', 'type': 'address'},
>         'salt': {'name': 'salt', 'type': 'bytes32'},
>     }
>     primaryType = _getPrimaryType(types, values)
>     newValue = _fix(values.copy(), primaryType, types)
>     EIP712Domain = []
>     for domainKey in domain:
>         EIP712Domain.append(EIP712DomainMap[domainKey])
>     newTypes = types.copy()
>     newTypes['EIP712Domain'] = EIP712Domain
>     newDomain = _fix(domain, 'EIP712Domain', newTypes)
>     completedStruct = {
>         "types": newTypes,
>         "domain": newDomain,
>         "message": newValue,
>         "primaryType": primaryType,
>     }
>     return completedStruct
> 
> s1 = '''{"types":{"SafeTx":[{"type":"address","name":"to"},{"type":"uint256","name":"value"},{"type":"bytes","name":"data"},{"type":"uint8","name":"operation"},{"type":"uint256","name":"safeTxGas"},{"type":"uint256","name":"baseGas"},{"type":"uint256","name":"gasPrice"},{"type":"address","name":"gasToken"},{"type":"address","name":"refundReceiver"},{"type":"uint256","name":"nonce"}],"EIP712Domain":[{"name":"chainId","type":"uint256"},{"name":"verifyingContract","type":"address"}]},"domain":{"chainId":"137","verifyingContract":"0x9135a7832db16190475f409b649771532bb6fa7f"},"primaryType":"SafeTx","message":{"to":"0x9135a7832db16190475f409b649771532bb6fa7f","value":"0","data":"0x694e80c30000000000000000000000000000000000000000000000000000000000000001","operation":"0","safeTxGas":"0","baseGas":"0","gasPrice":"0","gasToken":"0x0000000000000000000000000000000000000000","refundReceiver":"0x0000000000000000000000000000000000000000","nonce":"0"}}'''
> s1 = json.loads(s1)
> 
> signInfo = TypedDataConvert(s1['domain'], s1['types'], s1['message'])
> encodeData = encode_structured_data(signInfo)
> 
> res = Account.sign_message(encodeData, private_key='YOUR_PRIVATE_KEY')
> print(res.signature.hex())
> ```
> 
> is it correct!?
> 
> > > > gnosis safe signtypeddata
> > > 
> > > 
> > > would you give me "gnosis safe" website!?
> > > I can try and debug.
> > > I only try on blur.io, so i thought that it is generic code.
> > > Or you can post a sign info json here.
> > > P.S. if you can provide after sign result for compare
> > 
> > 
> > This whole data converting system must be considerably complicated for metamask to have a whole repo to deal with this.
> > [signtypeddatav4 metamask](https://docs.metamask.io/guide/signing-data.html#signtypeddata-v4)
> > The [eth-sig-util github repo](https://github.com/MetaMask/eth-sig-util) looks to contain all the signature structuring code in javascript only 🙄.

I put out a question on their (gnosis safe) question bulletin board to see what kind of formatting is expected for their signedTypedData.  Is this the type of clarification you need for safe.global to work with TypedDataConvert?

[stackexchange gnosis safe question](https://ethereum.stackexchange.com/questions/147230/difficulty-processing-requests-for-ethsignedtypedata-safe-signatures-in-python-t)

**Comment by snarflakes** [comment]
It is a key error here when trying to use your TypedDataConvert tool (which I don't think I posted for you yet). Thanks.

['0x827d3e01191de9206ce85197d1e1f2b91ed7251d', '{"types":{"SafeTx":[{"type":"add                                                                                                                                   ress","name":"to"},{"type":"uint256","name":"value"},{"type":"bytes","name":"dat                                                                                                                                   a"},{"type":"uint8","name":"operation"},{"type":"uint256","name":"safeTxGas"},{"                                                                                                                                   type":"uint256","name":"baseGas"},{"type":"uint256","name":"gasPrice"},{"type":"                                                                                                                                   address","name":"gasToken"},{"type":"address","name":"refundReceiver"},{"type":"                                                                                                                                   uint256","name":"nonce"}],"EIP712Domain":[{"name":"chainId","type":"uint256"},{"                                                                                                                                   name":"verifyingContract","type":"address"}]},"domain":{"chainId":"137","verifyi                                                                                                                                   ngContract":"0x9135a7832db16190475f409b649771532bb6fa7f"},"primaryType":"SafeTx"                                                                                                                                   ,"message":{"to":"0x9135a7832db16190475f409b649771532bb6fa7f","value":"0","data"                                                                                                                                   :"0x694e80c30000000000000000000000000000000000000000000000000000000000000001","o                                                                                                                                   peration":"0","safeTxGas":"0","baseGas":"0","gasPrice":"0","gasToken":"0x0000000                                                                                                                                   000000000000000000000000000000000","refundReceiver":"0x0000000000000000000000000                                                                                                                                   000000000000000","nonce":"0"}}']
<class 'str'>
{"types":{"SafeTx":[{"type":"address","name":"to"},{"type":"uint256","name":"val                                                                                                                                   ue"},{"type":"bytes","name":"data"},{"type":"uint8","name":"operation"},{"type":                                                                                                                                   "uint256","name":"safeTxGas"},{"type":"uint256","name":"baseGas"},{"type":"uint2                                                                                                                                   56","name":"gasPrice"},{"type":"address","name":"gasToken"},{"type":"address","n                                                                                                                                   ame":"refundReceiver"},{"type":"uint256","name":"nonce"}],"EIP712Domain":[{"name                                                                                                                                   ":"chainId","type":"uint256"},{"name":"verifyingContract","type":"address"}]},"d                                                                                                                                   omain":{"chainId":"137","verifyingContract":"0x9135a7832db16190475f409b649771532                                                                                                                                   bb6fa7f"},"primaryType":"SafeTx","message":{"to":"0x9135a7832db16190475f409b6497                                                                                                                                   71532bb6fa7f","value":"0","data":"0x694e80c3000000000000000000000000000000000000                                                                                                                                   0000000000000000000000000001","operation":"0","safeTxGas":"0","baseGas":"0","gas                                                                                                                                   Price":"0","gasToken":"0x0000000000000000000000000000000000000000","refundReceiv                                                                                                                                   er":"0x0000000000000000000000000000000000000000","nonce":"0"}}
load json
<class 'dict'>
{'types': {'SafeTx': [{'type': 'address', 'name': 'to'}, {'type': 'uint256', 'na                                                                                                                                   me': 'value'}, {'type': 'bytes', 'name': 'data'}, {'type': 'uint8', 'name': 'ope                                                                                                                                   ration'}, {'type': 'uint256', 'name': 'safeTxGas'}, {'type': 'uint256', 'name':                                                                                                                                    'baseGas'}, {'type': 'uint256', 'name': 'gasPrice'}, {'type': 'address', 'name':                                                                                                                                    'gasToken'}, {'type': 'address', 'name': 'refundReceiver'}, {'type': 'uint256',                                                                                                                                    'name': 'nonce'}], 'EIP712Domain': [{'name': 'chainId', 'type': 'uint256'}, {'n                                                                                                                                   ame': 'verifyingContract', 'type': 'address'}]}, 'domain': {'chainId': '137', 'v                                                                                                                                   erifyingContract': '0x9135a7832db16190475f409b649771532bb6fa7f'}, 'primaryType':                                                                                                                                    'SafeTx', 'message': {'to': '0x9135a7832db16190475f409b649771532bb6fa7f', 'valu                                                                                                                                   e': '0', 'data': '0x694e80c30000000000000000000000000000000000000000000000000000                                                                                                                                   000000000001', 'operation': '0', 'safeTxGas': '0', 'baseGas': '0', 'gasPrice': '                                                                                                                                   0', 'gasToken': '0x0000000000000000000000000000000000000000', 'refundReceiver':                                                                                                                                    '0x0000000000000000000000000000000000000000', 'nonce': '0'}}
137
Traceback (most recent call last):
  File "imageidopen.py", line 1012, in qr_capture
    signInfo = TypedDataConvert(parameters['data']['domain'], parameters['data']                                                                                                                                   ['types'], parameters['data']['value'])
KeyError: 'data'

**Comment by marktohark** [comment]
> 

parameters['data']['domain'] > parameters['domain']

**Comment by pacrob** [comment]
Thanks for all your work, @marktohark! This will be more familiar to users who know MetaMask's `signTypedData_v4` format. I think it could actually just be added as a new method `sign_typed_data_v4` so it's more easily recognized.

We do our best to avoid implicit type conversion, but I can see how it would be useful. Having a flag that defaults to `False` for type fixing might do it. The PR will need testing and docs updates before it can be included too. If you have time, great, otherwise I'll aim to put it together in the next week or two.

**Comment by marktohark** [comment]
What can i say. Lmao
It is not about my code wrong.
That is a easy error to solve, man.
Dont be a copier and paster, you shoud know what you are doing.

**Comment by snarflakes** [comment]
> What can i say. Lmao It is not about my code wrong. That is a easy error to solve, man. Dont be a copier and paster, you shoud know what you are doing.

Thanks again for all your help! I mistakenly thought TypedDataConvert could automatically process the entire exact json original dictionary signature request, I see now the original json has to be reviewed as it needs to be delivered with a small modification for each unique contract signature request.

Furthermore blur type specifically says: "signTypedData_v4"
while safe.global says "eth_signTypedData"?

**Pull request closed without merging**
