### PR TITLE
Ledger wallet support

### PR DESCRIPTION
**Pull request by pipermerriam**
Merging this work by @bargst into a local feature branch to put it on ice until we can dig into it later this year.

### CODE REVIEW

**Comment by livnev** [comment]
Hi, this feature (ledger support) is very useful. Is there a plan to review and merge this? cc @pipermerriam @bargst

**Comment by pipermerriam** [comment]
cc @kclowes

**Comment by kclowes** [comment]
No plan yet, but it keeps coming up so I think it may make sense to have it be the next big thing to tackle after async. I know @davesque spent some time digging in here too, but I'm not sure where he landed.

**Comment by davesque** [comment]
I was looking at HD wallet support which is a separate thing.

**Comment by kclowes** [comment]
Oops, I didn't actually read the title and thought this was the HD wallet branch. Sorry @davesque! @livnev Not sure when this will be queued up, but knowing that there is interest definitely helps bump it up in priority. We'll keep you posted!

**Comment by palkeo** [comment]
+1 it would be great to see that support.
Is merging that change blocked on proper support for HD wallets?

**Comment by fubuloubu** [comment]
It might be handy for testing purposes to use the SpeculOS simulator: https://github.com/LedgerHQ/speculos

**Comment by bargst** [comment]
good idea! I started the upgrade to latest eth-account, will see if I could add SpeculOS testing

**Comment by fubuloubu** [comment]
I've been trying out this excellent library with web3py integration as a signing middleware:
https://github.com/mikeshultz/ledger-eth-lib

Would be really, really, really awesome to have this finally supported as a production feature.

**Pull request merged**
